### ISSUE TITLE
DOI not working

### ISSUE THREAD

**Issue by blsqr** [distillpub/post--growing-ca#13]
Hi there,

the DOI `10.23915/distill.00023` specified in the citation information [here](https://distill.pub/2020/growing-ca/) does not appear to work: http://doi.org/10.23915/distill.00023 brings up an error page.

This came up in the context of a [JOSS paper review](https://github.com/openjournals/joss-reviews/issues/3608), where the author would like to properly cite the given article. Any chance this can be fixed?

**Comment by ludwigschubert** [comment]
Hi @blsqr and thank you for reporting!
I can verify that the doi is not currently registered. Our generated crossref metadata file is not valid — that usually happens because the article itself has an unusually structured citation in it, or if our generation code has a bug. I’m investigating.

**Comment by ludwigschubert** [comment]
@blsqr I have manually fixed the issue for now — the doi should work as intended. 

The cause was an invalidly generated XML file when citations contain an empty “volume” field. I’m these cases we should entirely omit the field — I have opened an issue on our internal tool. 

Thanks again for reporting, and feel free to reopen if theres any other issue preventing a proper citation. :-)

**Comment by blsqr** [comment]
Awesome, thank you for quickly addressing this, @ludwigschubert! :)
